### ISSUE TITLE
api-ms-win-crt-math-l1-1-0.dll is missing

### ISSUE THREAD

**Issue by Kuanlin-Chen** [picussecurity/picuslabs#1]
I got an error message, running on Windows Server 2012 R2.

**zerologon_tester.exe - System Error**
The program can't start because api-ms-win-crt-math-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by Kuanlin-Chen** [comment]
I can find the lib `api-ms-win-crt-math-l1-1-0.dll` on Windows 10, so it might be the server version's problem.

**Comment by EmreOvunc** [comment]
> I can find the lib `api-ms-win-crt-math-l1-1-0.dll` on Windows 10, so it might be the server version's problem.

I am unsure why this seems to be an issue on Windows Server 2012 R2. However, you can copy missing dlls manually.

* it is from Microsoft;

```
The missing dll's are installed with a Windows update. To resolve this, download¹ and install the Update for Universal C Runtime in Windows from Microsoft.

Note:
To install this update², you must have April 2014 update rollup for Windows RT 8.1, Windows 8.1, and Windows Server 2012 R2 (2919355) installed in Windows 8.1 or Windows Server 2012 R2.
```
¹ https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
² http://support.microsoft.com/kb/2919355

* somebody also said;
```
this error message can be cause due to Visual C++ Redistributable for Visual Studio 2015 RC³ fails on Windows Server 2012.
```
³ https://social.msdn.microsoft.com/Forums/vstudio/en-US/64baed8c-b00c-40d5-b19a-99b26a11516e/visual-c-redistributable-for-visual-studio-2015-rc-fails-on-windows-server-2012?forum=vssetup

**Comment by Kuanlin-Chen** [comment]
Thanks for sparing your time! Cause this issue is not relevant to this tool, it's a Windows issue, so I will close it.
